version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'my_database'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '102030'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '102030'
    networks:
      - gateway
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./containerVol/mysql:/var/lib/mysql


  apiNode:
      image: fullcycledesafio2_api:latest
      restart: always
      networks: 
        - gateway
      ports:
        - '3000:3000'
      expose:
        - '3000'
      depends_on:
      - db
         
# Names our volume

networks:
  gateway: {}

  # docker run -it --rm --name apiNode -v $(pwd)/code/:/usr/src/app -p 3000:3000 node:18 bash