version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'my_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '102030'
      MYSQL_ROOT_PASSWORD: '102030'
    networks:
      - gateway
    ports:
      - '3306:3306'
    expose:
      - '3306'
     
    volumes:
      - ./mysql:/var/lib/mysql


  apinode:
    build:
      context: ./apinode
    container_name: apinode
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    volumes:
      - ./apinode:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - gateway
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:8080"
    networks:
      - gateway
    depends_on:
      - apinode

networks:
  gateway: {}

  