version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'my_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '102030'
      MYSQL_ROOT_PASSWORD: '102030'
    networks:
      - gateway
    ports:
      - '3306:3306'
    expose:
      - '3306'
     
    #volumes:
    # - ./containerVol/mysql:/var/lib/mysql


  apiNode:
      image: thiagohmm/fullcycledesafio2_api:latest
      restart: always
      networks: 
        - gateway
      
      expose:
        - '3000'
      depends_on:
        - db

  reverseProxy:  
      image: thiagohmm/fullcycledesafio2_rproxy
      restart: always
      networks:
        - gateway
      ports:
        - '8080:8080'
      expose:
        - '8080'
      depends_on:
        - apiNode

networks:
  gateway: {}

  